### ISSUE TITLE
Dataset naming

### ISSUE THREAD

**Issue by jayqi** [invinst/shootings-data#46]
We can probably all agree that our current month designations for the datasets are not the most illuminative. 

I propose a new scheme of: `topic-source-monthyearofrelease`

So for example:
* May -> `shootings-ipra-may16`

I think datasets that correspond to the same FOIA request content should have the same topic name.

**Comment by DGalt** [comment]
I agree, I think your solution is a good one.

**Comment by jayqi** [comment]
Working names implemented with pull #54
