### ISSUE TITLE
Append February data to shootings-append.csv

### ISSUE THREAD

**Issue by alexsoble** [invinst/shootings-data#5]
Right now, `shootings-append.csv` includes only data from the April and May files.

The February file includes only three types of incident categories: 18A, 18B, 20A. It uses a very different column schema from the April and May files, and it has less information that the other two files.

We would like to merge it in to `shootings-append.csv`, but we need to figure out how to accurately map the column schemas onto each other given that February has less information.

**Comment by jayqi** [comment]
Merging into related #4
