### ISSUE TITLE
Migrate shootings-append files and related to somewhere else

### ISSUE THREAD

**Issue by jayqi** [invinst/shootings-data#50]
Since the effort to merge these datasets (issue #4) is not trivial and involves some significant interpretation on top of what is in the raw data files, I am suggesting that we consider it to be an independent project for now. In that case, we would want to migrate all files associated with `shootings-append` and `shootings-merge` to somewhere else.

**Comment by rajivsinclair** [comment]
Where is the new home for `shootings-append`? Will it only exist in the historic commits?

**Comment by jayqi** [comment]
I think you and @ithinkidunno have been the primary people working on that, so it's up to you where you want to put it. For now, I just removed them since they are still in the historic commits and can't be lost.

**Comment by rajivsinclair** [comment]
Got it.

**Comment by jayqi** [comment]
Going to close this since I've removed the files in the master branch with pull #54 

If anyone needs to get to them, this is the most recent commit that still has them: 
https://github.com/invinst/shootings-data/tree/97f2ec7fb52e6e167952fa2d25df2fdb8c1e426a
