### ISSUE TITLE
Repo directory structure

### ISSUE THREAD

**Issue by jayqi** [invinst/shootings-data#51]
As part of cleaning up the repository, we should determine a directory structure.

I personally would like something a little flatter than what we already have, so that people can see all of the datasets at a glance.

So in the root we have:
* `README.md` -- basic info about repo, issue tracker, tell people to look at wiki for more info
* `[datasetname]/` -- directories that contain the relevant files to the dataset
    * README.md -- basic info about that dataset
    * `cleaned_[datasetname].csv` -- cleaned up data (but without any processing that would require interpretation)
    * `raw/` -- subdirectory that contains raw data files and copies of FOIA correspondence
* `[datasetname]/`
    * ... (same)
* `[datasetname]/`
    * ... (same)
* `context/` -- basically the same as what we currently have, extra data files for contextual information. We should try to digitize everything into a machine readable format for things that aren't already. 

Naming is discussed separately in issue #46 

Migrating files associated with `shootings-append.csv` discussed in issue #50

**Comment by evanwsun** [comment]
That sounds fine to me, at least for the moment. Where do we plan to put the other data for now?

**Comment by jayqi** [comment]
Working on this here.

https://github.com/jayqi/shootings-data/tree/reorganization

For now, I'm planning on just removing `shootings-append.csv` and the individual CRID files. Those will still be available by going back to an earlier commit.

**Comment by jayqi** [comment]
Working implementation with pull #54
