### ISSUE TITLE
Finish COLUMN-DICTIONARY.txt

### ISSUE THREAD

**Issue by alexsoble** [invinst/shootings-data#9]
Let's set up a plan / target date for doing this @rajivsinclair @ithinkidunno.

**Comment by ithinkidunno** [comment]
How about Tuesday?

**Comment by alexsoble** [comment]
@ithinkidunno OK great. We will do this at Hack Night on Tuesday evening. Talking about each column out loud will be useful to help orient new volunteers who are interested in contributing. I remember we talked about this but forgot exactly where we landed, good to put it in writing. 👍

**Comment by ithinkidunno** [comment]
see you Tuesday!
